# Generated by Django 4.2.4 on 2023-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
