# Generated by Django 4.2.4 on 2023-08-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_personal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_phone',
            field=models.JSONField(default=list),
        ),
    ]
